mode = "client"
log_level = "debug" # optional

[trojan]
password = "password"

[socks5]
addr = "127.0.0.1:1080"

[tls]
addr = "example.com:443"
sni = "example.com"
cert = "cert.pem" # optional
# cipher = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"] # optional, TLS 1.2 only
# handshake_timeout_secs = 10

# optional
#[websocket]
#uri = "wss://example.com/trojanpath"
# handshake_timeout_secs = 10
# read_buffer_size = 16384
# write_buffer_size = 16384
# max_message_size = 1048576
# max_frame_size = 1048576
# max_write_buffer_size = 2097152

# optional
#[mux]
#concurrent = 8
#timeout = 30
