mode = "forward"
log_level = "debug" # optional

[dokodemo]
target_addr = "8.8.8.8:53"
listen_addr = "127.0.0.1:53"

[trojan]
password = "password"

[tls]
addr = "example.com:443"
sni = "example.com"
cert = "cert.pem" # optional
# cipher = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"] # optional, TLS 1.2 only
# handshake_timeout_secs = 10

# optional
# [websocket]
# uri = "wss://example.com/trojanpath"
